%% Static calibration
addpath('data');
filename_temp_bi='Temperature_bi_1431942285.53.txt';
rows_bi=[400 41500];
filename_temp_kj='Temperature_kj_1431899686.36.txt';
rows_kj=[700 45000];
workingtemperature=27.0;
dt=0.01;
[gbiasx_bi,gbiasy_bi,gbiasz_bi,...
    gsensx_bi,gsensy_bi,gsensz_bi,...
    gtimevarx_bi,gtimevary_bi,gtimevarz_bi,...
    mbiasx_bi,mbiasy_bi,mbiasz_bi,...
    msensx_bi,msensy_bi,msensz_bi,...
    mtimevarx_bi,mtimevary_bi,mtimevarz_bi,...
    atimevarx_bi,atimevary_bi,atimevarz_bi...
    ] = sensor_static_calibration(...
    filename_temp_bi,workingtemperature,dt,rows_bi(1),rows_bi(2));
[gbiasx_kj,gbiasy_kj,gbiasz_kj,...
    gsensx_kj,gsensy_kj,gsensz_kj,...
    gtimevarx_kj,gtimevary_kj,gtimevarz_kj,...
    mbiasx_kj,mbiasy_kj,mbiasz_kj,...
    msensx_kj,msensy_kj,msensz_kj,...
    mtimevarx_kj,mtimevary_kj,mtimevarz_kj,...
    atimevarx_kj,atimevary_kj,atimevarz_kj...
    ] = sensor_static_calibration(...
    filename_temp_kj,workingtemperature,dt,rows_kj(1),rows_kj(2));
filename_temp_out_bi=strcat(filename_temp_bi(1:end-4),'_static_calibration.txt');
filename_temp_out_kj=strcat(filename_temp_kj(1:end-4),'_static_calibration.txt');
format_bi=[...
    '#bi\n'...
    'gyro_offset_x = %3.14g\n'...
    'gyro_offset_y = %3.14g\n'...
    'gyro_offset_z = %3.14g\n'...
    'gyro_working_temperature = %3.1f\n'...
    'gyro_temperature_sensitivity_x = %3.14g\n'...
    'gyro_temperature_sensitivity_y = %3.14g\n'...
    'gyro_temperature_sensitivity_z = %3.14g\n'...
    'magn_temperature_sensitivity_x = %3.14g\n'...
    'magn_temperature_sensitivity_y = %3.14g\n'...
    'magn_temperature_sensitivity_z = %3.14g\n'...
    '#gyro_time_variance_x = %3.14g\n'...
    '#gyro_time_variance_y = %3.14g\n'...
    '#gyro_time_variance_z = %3.14g\n'...
    '#magn_time_variance_x = %3.14g\n'...
    '#magn_time_variance_y = %3.14g\n'...
    '#magn_time_variance_z = %3.14g\n'...
    '#acc_time_variance_x = %3.14g\n'...
    '#acc_time_variance_y = %3.14g\n'...
    '#acc_time_variance_z = %3.14g\n'...
    ];
fid_temp_out_bi = fopen(filename_temp_out_bi,'w');
fprintf(fid_temp_out_bi,...
    format_bi,...
    gbiasx_bi,gbiasy_bi,gbiasz_bi,...
    workingtemperature,...
    gsensx_bi,gsensy_bi,gsensz_bi,...
    msensx_bi,msensy_bi,msensz_bi,...
    gtimevarx_bi,gtimevary_bi,gtimevarz_bi,...
    mtimevarx_bi,mtimevary_bi,mtimevarz_bi,...
    atimevarx_bi,atimevary_bi,atimevarz_bi);
fclose(fid_temp_out_bi);
format_kj=[...
    '#kj\n'...
    'gyro_offset_x = %3.14g\n'...
    'gyro_offset_y = %3.14g\n'...
    'gyro_offset_z = %3.14g\n'...
    'gyro_working_temperature = %3.1f\n'...
    'gyro_temperature_sensitivity_x = %3.14g\n'...
    'gyro_temperature_sensitivity_y = %3.14g\n'...
    'gyro_temperature_sensitivity_z = %3.14g\n'...
    'magn_temperature_sensitivity_x = %3.14g\n'...
    'magn_temperature_sensitivity_y = %3.14g\n'...
    'magn_temperature_sensitivity_z = %3.14g\n'...
    '#gyro_time_variance_x = %3.14g\n'...
    '#gyro_time_variance_y = %3.14g\n'...
    '#gyro_time_variance_z = %3.14g\n'...
    '#magn_time_variance_x = %3.14g\n'...
    '#magn_time_variance_y = %3.14g\n'...
    '#magn_time_variance_z = %3.14g\n'...
    '#acc_time_variance_x = %3.14g\n'...
    '#acc_time_variance_y = %3.14g\n'...
    '#acc_time_variance_z = %3.14g\n'...
    ];
fid_temp_out_kj = fopen(filename_temp_out_kj,'w');
fprintf(fid_temp_out_kj,...
    format_kj,...
    gbiasx_kj,gbiasy_kj,gbiasz_kj,...
    workingtemperature,...
    gsensx_kj,gsensy_kj,gsensz_kj,...
    msensx_kj,msensy_kj,msensz_kj,...
    gtimevarx_kj,gtimevary_kj,gtimevarz_kj,...
    mtimevarx_kj,mtimevary_kj,mtimevarz_kj,...
    atimevarx_kj,atimevary_kj,atimevarz_kj);
fclose(fid_temp_out_kj);

clear all